### ISSUE TITLE
Shaman Call of Water (Part 6) Class Quest Bug

### ISSUE THREAD

**Issue by Blocka123** [WoWFeenix/Warsong-Realm#11]
**When it occured: **
After Killing the Corrupt Minor Manifestation of Water
**Description: **
Mob does not drop the necesary items to clikc on the brazier and complete the quest.
**How it works: **
Mob does not drop items
**How it should work: **
Mob should drop quest items 
**Link to WoWHead/WoWWiki: **
https://classicdb.ch/?quest=63

**Comment by WoWFeenix** [comment]
Unfortunately, we are not able to recreate this bug. Please report it again with the proof.
