### ISSUE TITLE
Taming the beast(orc and troll 1)

### ISSUE THREAD

**Issue by hunterman224** [WoWFeenix/Warsong-Realm#12]
**When it occured: ** 2nd part of the hunter chain to get pet

**Description: ** Dire Mottled Boar was an invalid target to tame, did this at level 14 which may have been causing the issue

**How it works: ** Target Dire mottled boar, use quest item, invalid target

**How it should work: ** the item should allow me to start taming the boar

**Link to WoWHead/WoWWiki: **http://wowwiki.wikia.com/wiki/Quest:Taming_the_Beast_(Orc_and_Troll_1)

**Comment by Farsun23** [comment]
I did this at level 13 and no issue.

**Comment by WoWFeenix** [comment]
Unfortunately, we are not able to recreate this bug. Please report it again with the proof.
