### ISSUE TITLE
Stealth on Furbolg

### ISSUE THREAD

**Issue by thebyq** [WoWFeenix/Warsong-Realm#14]
**When it occured: ** 19.05 2PM

**Description: ** Druids have possibility to become invisible (from cat form) while they're morphed to Furbolg

**How it works: **

**How it should work: ** When druids are morphed to Furbolg they shouldn't be able to use cat skills

**Link to WoWHead/WoWWiki: **

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will updete it tomorrow.
