### ISSUE TITLE
[Quest] Spirits of Stonetalon

### ISSUE THREAD

**Issue by lordyoyo** [WoWFeenix/Warsong-Realm#15]
When it occured: at date of this report
Description: The quest Spirits of Stonetalon, part of a long chain, is not finishable. The NPC doesn't talk to me, so I can't complete it, essentially blocking the whole chain. It's a level 13 quest, recommended for 17, I'm 23, so no issues there.
How it works: You pick up the quest, and can't complete it.
How it should work: You pick up the quest and you should be able to complete it.
Link to WoWHead/WoWWiki: https://classicdb.ch/?quest=1061
https://classicdb.ch/?npc=4049#ends

**Comment by WoWFeenix** [comment]
Unfortunately, we are not able to recreate this bug. Please report it again with the proof.

**Comment by lordyoyo** [comment]
yeah, it works now, so I'm guessing this was fixed. still doesn't work as intended though, because it gives out the next quest in the quest line regardless of having done the first one, but I don't care anymore :p
