### ISSUE TITLE
Bug on Mission: Possible But Not Probable

### ISSUE THREAD

**Issue by akeba1** [WoWFeenix/Warsong-Realm#22]
When: 20:25 GMT 20/05/2018
Description: In the Venture Co. tower, was unable to use abilities, receiving 'Internal Error' messages. Dying in the tower you don't revert to ghost form and the world appears normal, except for being unable to see mobs and able to walk on water. There is no normal death buff/debuff icon.
How it works: After dying, upon logging out and back in you resume being alive with 1 hp.
How it should work: Abilities should be usable and death should result in the normal process.
WoWhead: http://www.wowhead.com/quest=2478/mission-possible-but-not-probable

**Comment by WoWFeenix** [comment]
Can't confirm anymore, seems to be resolved with fixes for global aspects. If this error occur again, please report it with SS. Thank you.
