### ISSUE TITLE
Razormane Stalkers combat range way to long

### ISSUE THREAD

**Issue by Twet** [WoWFeenix/Warsong-Realm#24]
**When it occured: **
While doing "Weapons of choice" in Southern Barrens.
**Description: **
The Razormane Stalkers would come out of stealth, to attack me. If i try to outrun them, they will chase me for a while, then instead of running back, they go stealth again and keep chasing me in stealth until they killed me.
**How it works: **
Basicly they keep chasing me till i die.
**How it should work: **
They should be running back like normal melee mobs and then stealth when they are back at start point. 
**Link to WoWHead/WoWWiki: **
https://classicdb.ch/?npc=3457

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will update it tomorrow.
