### ISSUE TITLE
Kravel Koalbeard

### ISSUE THREAD

**Issue by ZackForester** [WoWFeenix/Warsong-Realm#26]
**When it occured: **
When trying to turn in the quest Rocket Car Parts.
**Description: **
NPC is unresponsive.
**How it works: **
NPC doesn't have a dialogue box.
**How it should work: **
NPC should have interaction options to turn in quests.
**Link to WoWHead/WoWWiki: **
http://wowwiki.wikia.com/wiki/Kravel_Koalbeard

**Comment by WoWFeenix** [comment]
Can't confirm anymore, seems to be resolved with fixes for global aspects. If this error occur again, please report it with SS. Thank you.
