### ISSUE TITLE
[big issue]! Evading mobs

### ISSUE THREAD

**Issue by Precisely11** [WoWFeenix/Warsong-Realm#27]
**When it occured: ** Whenever you are on a higher level ground or plane after you are already fighting an npc while the npc is chasing you

**How it works: ****Description: ** Lets say you kite 2 mobs and jump up on a higher ground and the mobs are taking on their path to you around some objects, meanwhile you are unable to hit them because they Evade and they regain hp until they reach you, then you can damage them once again.

**How it works: ** This shouldnt happen, I cant do my mage kiting because of this bug and its really frustrating, I bet Im not alone on this one.
Why do mobs evade in the middle of combat...

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will updete it tomorrow.
