### ISSUE TITLE
[Warrior] Berserker Rage does not award extra rage on damage taken

### ISSUE THREAD

**Issue by warlorddrak** [WoWFeenix/Warsong-Realm#29]
**How it works**

Aggro a mob with and without Berserker Rage, observe the Rage awarded just from damage taken.
You will notice, that you do not get any bonus rage.

**How it should work**

The warrior should get extra rage from damage taken for the duration of the effect. The exact formula might need to be researched.

This skill is broken on almost all pservers, the original Feenix project got it fixed eventually.

**Links to WoWHead/WoWWiki**

[Berserker Rage](https://classicdb.ch/?spell=18499) (skill description)
[Rage mechanic on wowwiki (history)](http://wowwiki.wikia.com/wiki/Rage?action=history), more info on exact mechanic is needed

**Comment by WoWFeenix** [comment]
Unfortunately, we are not able to recreate this bug. Please report it again with the proof.

**Comment by warlorddrak** [comment]
You are correct, I gathered real data today. An indeed I get one additional rage point with every hit.

* Warrior with 3830 armor, in berserker stance
* Hunter attacking with bow
* Each hit was recorded independently, at 0 rage, max one hit under the effect of Berserker Rage per cooldown

```
# Dmg received, Rage generated

## Without Berserker Rage

170, 1
149, 1
171, 1
171, 1
172, 1
153, 1
145, 1
175, 1
151, 1
162, 1
145, 1
151, 1
151, 1
176, 1
172, 1
168, 1
341, 3 (crit)
325, 3 (crit)
338, 3 (crit)
173, 1
157, 1

## With Berserker Rage

159, 2
326, 4 (crit)
176, 2
304, 4 (crit)
175, 2
159, 2
179, 2
170, 2
```
