### ISSUE TITLE
DMN - Tribute Chest

### ISSUE THREAD

**Issue by MrSanten** [WoWFeenix/Warsong-Realm#3]
**When it occured: **

**Description: **The Tribute chest doesn't spawn when you talk to Mizzle the Crafty also you don't recive the https://classicdb.ch/?spell=22799 buff when talking to him either which leaves the mobs hostile even after running back to receive all your buffs.

EDIT : After running out and into the dungeon again up to Mizzle the Crafty he gives me the buff but he still doesn't spawn the tribute chest.

**How it works: **

**How it should work: **

**Link to WoWHead/WoWWiki: **

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will updete it tomorrow.
