### ISSUE TITLE
Mountaineer Rockgar

### ISSUE THREAD

**Issue by ZackForester** [WoWFeenix/Warsong-Realm#30]
**When it occured: **
When killing an NPC.
**Description: **
Killing Mountaineer Rockgar awarded a dishonorable kill.
**How it works: **
Kill Mountaineer Rockgar and get a dishoorable kill notification.
**How it should work: **
Killing PvP NPCs should not award Dishonorable Kills. Only killing civilians should award dishonorable kills.
**Link to WoWHead/WoWWiki: **
http://wowwiki.wikia.com/wiki/Mountaineer_Rockgar

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will update it tomorrow. (May require WDB delete)
