### ISSUE TITLE
DM Tribute chest bugged & Cho'rush the Observer

### ISSUE THREAD

**Issue by blade7606** [WoWFeenix/Warsong-Realm#32]
**When it occured:  5/22/18 15:30 server time**

**Description: After killing the king in DM north tribute run the mini boss Cho'rush the Observer doesn't deaggro at all. In addition it is possible to bug out the tribute chest by having it despawn**

**How it works: After killing King Gordok, Cho'rush continues to kill the group. After talking to the Gordok npc that makes you the new king and friendly he will spawn the Gordok Tribute Chest. If someone talks to him after spawning the Gordok Tribute Chest, it will cause the chest to despawn. **

**How it should work: After killing King Gor'dok, Cho'rush should deaggro and become friendly. Afterwards the first player to talk to the Gordok NPC to make them the new king should spawn the chest after some follow up dialogue. After the chest is spawned, additional player should be able to talk to the friendly gordok NPC and it should not despawn the Gordok Tribute Chest.**

**Link to WoWHead/WoWWiki: http://wowwiki.wikia.com/wiki/Dire_Maul_tribute_run
http://www.wowhead.com/npc=11501/king-gordok
http://www.wowhead.com/object=179564/gordok-tribute
 **

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will update it tomorrow.
