### ISSUE TITLE
Mage Chill effect bug

### ISSUE THREAD

**Issue by dubbyz** [WoWFeenix/Warsong-Realm#38]
**When it occured: Few times yesterday and today**

**Description: Cone of Cold slow being ignored when Chilled effect from Blizzard is still on the target (With the talent Permafrost which increases the duration of the Chilled effect by 3 seconds)**

**How it works: So when I use Blizzard and the Chill effect is still on the mobs and use Cone of Cold it does not apply the slow from Cone of Cold.**

**How it should work: The slow from Cone of Cold should override the Chilled effect from Blizzard**

**Link to WoWHead/WoWWiki: Don't have one but this is how it works on Lights Hope.**

**Comment by WoWFeenix** [comment]
Unfortunately, we are not able to recreate this bug. Please report it again with the proof. 

Please have on mind if you got 3 / 3 in Improved Blizzard then debuff from Blizzard is at 65 % so CoC won't override stronger debuff.
