### ISSUE TITLE
Suppression Room - BWL

### ISSUE THREAD

**Issue by MrSanten** [WoWFeenix/Warsong-Realm#4]
**When it occured: **

**Description: **While in stealth, you are suppose to deactivate the suppression device once its done it remove stealth but its should not remove stealth.

**How it works: **

**How it should work: **

**Link to WoWHead/WoWWiki: **

**Comment by WoWFeenix** [comment]
Unfortunately, we are not able to recreate this bug. Please report it again with the proof.
