### ISSUE TITLE
Warsong Marks in Mail

### ISSUE THREAD

**Issue by Badlands2015** [WoWFeenix/Warsong-Realm#48]
Normally items in the mail sit there for 30 days. Currently, this is limited to 24 hours. Since we don't have marks for gold at the moment, I can't turn those marks in for anything but honor when I wanted to save them for gold turn ins.

**Comment by warlorddrak** [comment]
Can be closed now, I guess.

To turn in all Warsong marks in your inventory for gold (2g each), type:

```
.mark wsg
```
