### ISSUE TITLE
Feral Charge bear form.

### ISSUE THREAD

**Issue by crisvdn** [WoWFeenix/Warsong-Realm#50]
**When it occured: **24 may 2018

**Description: ** Feral charge

**How it works: **Currently it locks/interrupts the NPC into place. It doesn't stop spell casting and doesn't immobilize.

**How it should work: ** It should stop spell casting and should immobilize for 4 seconds(according to description of feral charge)

**Link to WoWHead/WoWWiki: **
http://www.wowhead.com/spell=79870/feral-charge

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will updete it tomorrow.
