### ISSUE TITLE
NPC Donova Snowden

### ISSUE THREAD

**Issue by shadowbola** [WoWFeenix/Warsong-Realm#68]
**When it occured: ** 05/28/2018 6:49 PM

**Description: ** I have some quests to finish on this NPC, but it doesnt show. 

**How it works: ** Dont work

**How it should work: ** I could finish the quest on this NPC

**Link to WoWHead/WoWWiki: ** 
http://wowwiki.wikia.com/wiki/Quest:Mystery_Goo
http://wowwiki.wikia.com/wiki/Donova_Snowden

**Comment by warlorddrak** [comment]
Duplicate of #19

**Comment by WoWFeenix** [comment]
Duplicate of #19
