### ISSUE TITLE
[Minor bug - vanity item ] Piccolo of the Flaming Fire

### ISSUE THREAD

**Issue by MrSanten** [WoWFeenix/Warsong-Realm#7]
**When it occured: **

**Description: **http://www.wowhead.com/item=13379/piccol...aming-fire dosent make ppl /dance
the sound works and it can be heard by everybody in 5 yards radius but ppl dont dance

**How it works: **

**How it should work: **

**Link to WoWHead/WoWWiki: **

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will updete it tomorrow.
