### ISSUE TITLE
Missing NPC/Quests - Light's Hope

### ISSUE THREAD

**Issue by MrSanten** [WoWFeenix/Warsong-Realm#8]
**When it occured: **

**Description: **From what i can tell the NPCs and the quests are missing in Light's hope that will give

Quest
http://www.wowhead.com/quest=9127/bone-fragments
http://www.wowhead.com/quest=9125/crypt-fiend-parts
http://www.wowhead.com/quest=9132/dark-iron-scraps
http://www.wowhead.com/quest=9136/savage-flora
http://www.wowhead.com/quest=9129/core-of-elements

Rewards
http://www.wowhead.com/item=22524/insign...he-crusade
http://www.wowhead.com/item=22523/insignia-of-the-dawn

**How it works: **

**How it should work: **

**Link to WoWHead/WoWWiki: **

**Comment by Farsun23** [comment]
These are likely not implemented due to the fact that they are apparently scaling raids.

**Comment by WoWFeenix** [comment]
Unfortunately, we are not able to recreate this bug. Please report it again with the proof.
