### ISSUE TITLE
Onyxia issues

### ISSUE THREAD

**Issue by Twet** [WoWFeenix/Warsong-Realm#86]
ISSUE 1:

** Onyxia phase 3 **

** She does a knockback, during fear she randomly turned and knocked a healer up on one of the side ledges. This healer got aggro right away, and she did a softreset. We had her on 3% and she went instantly up to 20%**

She is not supposed to reset if a person on a ledge gets aggro, also the whelps does nothing if aggroed by a person on a ledge I noticed.

ISSUE 2:

** Onyxia Loot*

She only dropped 2x t2 head (priest/shaman), 2x eskhandar's collar, 0 head of onyxia and 0 backpack. However we did get 2 sack of gems.

This is 2x or 4x or whatever you call the droprate. So according to my calculations we are supposed to get 4x t2 heads, 4x random items from her loottable, 2x head of onyxia, 2x backpacks and 2x sack of gems.

I do realize that with super bad rng, we could maybe have rolled 2x paladin t2 head we wouldn't be able to see as we are horde, but looking at the rest of the loot we got, it looks more like a bug to me with drop rates and also drop %.

**Comment by WoWFeenix** [comment]
This issue has been fixed. We will updete it tomorrow.
