### ISSUE TITLE
Completing "The Battle for Alterac"  does not open up "Hero of the Frostwolf"

### ISSUE THREAD

**Issue by maronics** [WoWFeenix/Warsong-Realm#88]
Completing the quest "The Battle for Alterac" (http://classicdb.ch/?quest=7142) does not open up the follow up quest "Hero of the Frostwolf" (http://classicdb.ch/?quest=8272) as it should. 

I'd guess alliance has the same issue with their respective quests, can't confirm. (The Battle of Alterac http://classicdb.ch/?quest=7141 & Hero of the Stormpike http://classicdb.ch/?quest=8271)

**Comment by Shirafari** [comment]
Can confirm, NPC doesn't give the follow-up quest on Alliance too

**Comment by WoWFeenix** [comment]
Resolved.
