### ISSUE TITLE
Trade Leashing

### ISSUE THREAD

**Issue by 510Kyle** [WoWFeenix/Warsong-Realm#9]
**When it occured: **

**Description: **
When you open a trade while someone is moving it instantly cancels with no room at all.
**How it works: **

**How it should work: **
There's suppose to be a slightly longer leash so obviously they can run away and cancel but it shouldn't auto cancel the second you put it up.
**Link to WoWHead/WoWWiki: **

**Comment by Farsun23** [comment]
Can confirm, happened numerous times to myself when attempting to trade a fellow player.

**Comment by WoWFeenix** [comment]
Unfortunately, we are not able to recreate this bug. Please report it again with the proof.
